### ISSUE TITLE
Add some CI?

### ISSUE THREAD

**Issue by bilalbox** [ajoldham/apache#1]
Just a thought for a fun exercise:

What do you think of adding some CI workflows to this so that a commit kicks off a job to automatically build and push the image to a registry based on passing some simple tests? Maybe using [travis](https://travis-ci.org) or [circle](http://circleci.com)?

**Comment by ajoldham** [comment]
?

**Comment by ajoldham** [comment]
Seems far off the main objective of providing a simple web server.
